const SUPABASE_URL = "https://phggtslcefmhmksiupqt.supabase.co";
const SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBoZ2d0c2xjZWZtaG1rc2l1cHF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg2MzQ5MDUsImV4cCI6MjA5NDIxMDkwNX0.OmHqa90Ph6Jj96rEbnlr10kOuize8wqlPqIcLgvZMQY";

export const supabase = window.supabase.createClient(SUPABASE_URL, SUPABASE_KEY);
